### ISSUE TITLE
class TaskType has no attribute 'TURN'

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#13]
Hello,

In documentation http://aerofiles.readthedocs.org/en/latest/api/xcsoar.html we can find 

    with writer.write_point(type=TaskType.TURN):
        writer.write_waypoint(...)
        writer.write_observation_zone(...)

but class `TaskType` has no attribute `TURN`

it should be `PointType` instead of `TaskType`

I also wonder why not using Eum34 for constants ?
https://docs.python.org/3/library/enum.html
https://pypi.python.org/pypi/enum34

Kind regards

**Comment by Turbo87** [comment]
@scls19fr good catch, thanks! could you prepare a pull request with the documentation fix?

I think when I started writing this lib I simply wasn't aware of Enum34, or maybe it didn't even exist yet.

**Comment by scls19fr** [comment]
Yes Enum34 is a port of Python 3 enum. It's quite recent.

**Comment by scls19fr** [comment]
PR sent.
