### ISSUE TITLE
Latest doc is not deployed on RTD

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#137]
Hello,

On https://aerofiles.readthedocs.io/en/latest/ we can read
 
> This part of the documentation, which is mostly prose, begins with some background information about Flask, then focuses on step-by-step instructions for web development with Flask.

but it was fixed by https://github.com/Turbo87/aerofiles/pull/100

So I think latest (ie dev version or instable version) doc is not deployed on RTD.

Kind regards

**Comment by bubeck** [comment]
Update done
