### ISSUE TITLE
Google Maps API and Google Earth

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#14]
Hello,

maybe this's a bit out of the scope of your project but when you have a XCSoar task file (or any other PNA), it will be nice to be able to draw this task on a map with much more details.

A webpage using Google Maps API could be an interesting idea.
Maybe Aerofiles should be able to output such a HTML page (or a link to webpage).
pygmaps or pygmaps-extended might help https://code.google.com/p/pygmaps/ https://github.com/thearn/pygmaps-extended

Having this task displayed in Google Earth will be also interesting as we can have 3D view.
pyKML could help http://googlegeodevelopers.blogspot.fr/2012/01/introducing-pykml-python-library-for.html

Kind regards

**Comment by Turbo87** [comment]
@scls19fr  you are right, this is out of scope, but we are planning to allow something like this in https://github.com/skylines-project/skylines

**Comment by scls19fr** [comment]
Thanks for the link. This is a very interesting project.
