### ISSUE TITLE
KML files support

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#141]
Hello,

I own a GPS Bluetooth logger (Dual XGPS160).
Being able to create GPX file or IGC file (without declaration) from KML file (with `gx:Track` should probably be supported). See [sample.kml](https://gist.github.com/scls19fr/c2ac0cceff917fac8d4a1a0a674b1a1d)

My first try was to use [pykml](https://pythonhosted.org/pykml/) but it doesn't seems to be maintained anymore .

Then I tried to use [simplekml](https://simplekml.readthedocs.io/en/latest/) but that's only a KML generator not a KML parser (see [code](https://bitbucket.org/KyleLancaster/simplekml/src))

Then I tried to use [fastkml](https://fastkml.readthedocs.io/en/latest/)... and found that `gx:Track` is not supported https://github.com/cleder/fastkml/issues/37

So I wrote my own code using ElementTree https://github.com/cleder/fastkml/issues/37#issuecomment-552215225

Maybe adding support of KML files with `gx:Track` to [aerofiles](https://github.com/Turbo87/aerofiles/) could be an interesting idea.

Kind regards

**Comment by bubeck** [comment]
I think gpsbabel would do the trick for you. Have you tried this?
