### ISSUE TITLE
TZO / TZN

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#146]
https://github.com/Turbo87/aerofiles/blob/61c0de5cdf870d7feb5cafbdc677c93b750a0e12/aerofiles/igc/reader.py#L351

uses TZO as Two Letter Code but such TLC doesn't seems to exist in IGC specification http://www.ukiws.demon.co.uk/GFAC/documents/tech_spec_gnss.pdf

**Comment by bubeck** [comment]
You are right. However, I assume, that there is a flight recorder, that (wrongly) uses TZO instead of TZN.
Parser could be improved by allowing TZO only for certain FTY
