### ISSUE TITLE
satelite(s) typo

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#147]
https://github.com/Turbo87/aerofiles/blob/61c0de5cdf870d7feb5cafbdc677c93b750a0e12/aerofiles/igc/reader.py#L292

should be `satellites` instead

**Comment by Turbo87** [comment]
😱  can you open a PR to fix this?

**Comment by scls19fr** [comment]
https://github.com/Turbo87/aerofiles/pull/148 is ready for review
