### ISSUE TITLE
History of task declaration is not kept

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#154]
Hello,

After reading at http://www.ukiws.demon.co.uk/GFAC/documents/tech_spec_gnss.pdf p26 about C RECORD - TASK (Pre-flight Declaration), it seems to me that an IGC file can have several tasks declared and "a declaration continues to be valid until it is replaced by a new one".

So there's at a given instant only one active task but several tasks can exist in a whole IGC file.

Reading at

https://github.com/Turbo87/aerofiles/blob/4dc41ca08d39ff9eb3be7eb57218e2d21e1e2745/aerofiles/igc/reader.py#L70

it seems that history of tasks in not kept in your implementation and maybe it should be considered.

An implementation could be to have

https://github.com/Turbo87/aerofiles/blob/4dc41ca08d39ff9eb3be7eb57218e2d21e1e2745/aerofiles/igc/reader.py#L31

replaced by

    task = [[], []]

and have 

https://github.com/Turbo87/aerofiles/blob/4dc41ca08d39ff9eb3be7eb57218e2d21e1e2745/aerofiles/igc/reader.py#L68-L73

replaced by

```python
 if task_item['subtype'] == 'task_info': 
     del task_item['subtype']
     task_item["waypoints"] = []
     task[1].append(task_item)
 elif task_item['subtype'] == 'waypoint_info': 
     del task_item['subtype'] 
     task[1]['waypoints'].append(task_item) 
```

I haven't tested it as I'm currently working on my [Julia implementation](https://github.com/scls19fr/IGC.jl) but would be very pleased to have your opinion about my interpretation of this.

Kind regards

**Comment by Turbo87** [comment]
hmm, I guess that could be interpreted like that. but since it has to appear before the first `B` record I'm wondering if that actually makes sense. I would assume it means: if you switch off the flight recorder, switch it on again on another day the same task declaration should still be active.

in all of the IGC files I've seen so far I've never encountered one with multiple task declarations.

**Comment by scls19fr** [comment]
my guess was that some IGC loggers accept changing task during flight but in such a case declaration of a second task could only occur after some B records (covered by first task declaration).

**Comment by Turbo87** [comment]
> some IGC loggers accept changing task during flight

nope, that is strictly forbidden. the task must be set prior to takeoff and can not be changed anymore afterwards.

**Comment by scls19fr** [comment]
Well! so this part of IGC spec is quite unclear because "The lines for Takeoff and Landing are for information and are not part of the official IGC Declaration".
I have never seen IGC file with multiple task declarations but it seems to be possible by replacing a task declaration by a new one.
Maybe we should ask for clarification to the GFAC = The IGC GNSS Flight Recorder Approval Committee especially to its chairman at the time of publication of spec (Ian Strachan).
Your opinion?

**Comment by Turbo87** [comment]
> so this part of IGC spec is quite unclear because "The lines for Takeoff and Landing are for information and are not part of the official IGC Declaration".

while that is true, most FRs these days have an automatic takeoff/landing detection and will only start the IGC file recording once takeoff is detected. others even require you to restart the device after a task declaration (e.g. Flarm).

**Comment by scls19fr** [comment]
An other part of spec seems to prove what your are saying...

p4 of pdf (page named iii)

```
Appendix A – The IGC Data File Standard
A3 Single Instance Data Records (A, H, I, J, C, D, G Records)
A4 Multiple Instance Data Records (B, E, F, K, L Records)
```

C records are single instance data records.

**Comment by bubeck** [comment]
This issue is quite old and I dont see a clear bug/recommendation/feature request. 
Could you please provide an IGC file that shows what you are requesting. If it is pure theoretical, then I want to close it, until we find a IGC file which shows the problem. Please reopen then.
