### ISSUE TITLE
Just what I wanted, but!

### ISSUE THREAD

**Issue by tobiz** [Turbo87/aerofiles#17]
Just what I wanted to output IGC format files, excellent. One small point you don't say what units '*_alt" is in.  I guess in the IGC format spec it says but it would make life easier for the user of aerofiles if it was stated in the documentation.

**Comment by Turbo87** [comment]
Feel free to open a PR :wink:

**Comment by tobiz** [comment]
So I did what I should have done and looked up the IGC format spec and the answer is "metres"; unsurprisingly!
