### ISSUE TITLE
alternate date syntax failure

### ISSUE THREAD

**Issue by UlysseV** [Turbo87/aerofiles#175]
Some IGC file have an alternate syntax for the date: instead of `HFDTE280709`, it uses `HFDTEDATE: 280709,01`.
I have seen this in files generated with the XCTrack app.
In this situation, aerofiles fails to read the date, which is then missing from the header data.

**Comment by bubeck** [comment]
You are right. The "H" parsing is incomplete. Currently it is able to work with short form only ("HFxxx") and not the long form with a colon. This is not only true for HFDTE but all other subtypes. I will extend aerofiles to work with this as well.

**Comment by bubeck** [comment]
Fixed with https://github.com/Turbo87/aerofiles/pull/246
