### ISSUE TITLE
new version on pip?

### ISSUE THREAD

**Issue by GliderGeek** [Turbo87/aerofiles#26]
the library has been updated with the following additions, which are currently not available pip:
- read the tasks from cup files
- read IGC files

**Comment by Turbo87** [comment]
@GliderGeek you should be able to release a new version (I'd suggest v0.4).

1) add a commit like https://github.com/Turbo87/aerofiles/commit/c703e46caadcca542bbd95e9f50daaf8623a7c57
2) add a tag on that commit like https://github.com/Turbo87/aerofiles/releases/tag/v0.3 (`v0.4` in this case)
3) push both commit and tag to this repo
4) TravisCI should take care of the rest

**Comment by GliderGeek** [comment]
ough, that was quite painful. a lot of problems with travis :(
managed to do it in the end, with python3.5 and python3.6 now supported 💪
