### ISSUE TITLE
too long igc line skipped

### ISSUE THREAD

**Issue by GliderGeek** [Turbo87/aerofiles#28]
SeeYou competition adds competition details in the L records (comments) of the IGC file. These records may exceed the maximum line length and are thus skipped in the parsing. This information is sometimes very useful and not indicative of a file error. For instance the task rules are presented like this. The `TaskTime=03:30:00` tells that this task is an AAT, but this can never be recovered after parsing, because the line is left out:

```
LSEEYOU OZ=-1,Style=2,R1=5000m,A1=180,Line=1
LSEEYOU OZ=0,Style=1,R1=20000m,A1=180
LSEEYOU OZ=1,Style=1,R1=20000m,A1=180
LSEEYOU OZ=2,Style=1,R1=40000m,A1=180
LSEEYOU OZ=3,Style=1,R1=2000m,A1=180
LSEEYOU OZ=4,Style=3,R1=500m,A1=180,Move=1,Reduce=1,Line=1
LSEEYOU TSK,NoStart=13:29:00,TaskTime=03:30:00,WpDis=False,MinDis=True,NearDis=0.5km,NearAlt=200.0m,MinFinAlt=0.0km
```

Maybe it would be an idea to add a flag for relaxing the maximum line length requirement on L records?

**Comment by Turbo87** [comment]
> Maybe it would be an idea to add a flag for relaxing the maximum line length requirement on L records?

yep, I have no idea why we have line length limits for this at all... 🤔

**Comment by GliderGeek** [comment]
This is implemented following the IGC spec ([FAI doc, section A2.1](https://www.fai.org/sites/default/files/documents/igc_fr_spec_with_al4a_2016-4-10.pdf)):

> An IGC-format file consists of lines of characters, each line giving a set of data such as for a GNSS fix. Each line starts with an upper-case letter denoting one of the Record types listed in para A2.2., and ends with CRLF (Carriage Return Line Feed). **Each line is limited to 76 characters in length**, excluding the CRLF which is hidden and does not appear in text form.

The idea was to skip invalid B records, such as the following (from this IGC):

```
B1023084948920N01509065EA0183501916006000
B1023134948940N01509187EA0184701922006000
BÿÿÿøÄÀÈÌÄàÐäÐàààÁ8ÀÄÔÀäÈÌåÀÄàÔäÀÄäÌØÀÀØÀÀÀ4)ÄÀÈÌÈÌÐäÐààÐÙ8ÀÄÔÀäÄÐÝÀÄàÜÌÀÄäÔàÀÀØÀÀÀ4)ÄÀÈÌÈàÐäÐàààÑ8ÀÄÔÀäÀÔÉÀÄàààÀÄäÜÈÀÀØÀÀÀ4)ÄÀÈÌÌÌÐäÐàäØÅ8ÀÄÔÀäÀÜáÀÄàääÀÄäÜÐÀÀØÀÀÀ4)ÄÀÈÌÌàÐäÐàäÜÕ8ÀÄÔÀäÈÄÁÀÄäÀÀÀÄäÜÀÀÀØÀÀÀ4)ÄÀÈÌÐÌÐäÐàäÄÝ8ÀÄÔÀäÈàáÀÄäÀÌÀÄäàÈÀÀØÀÀÀ4)ÄÀÈÌÐàÐäÐààØÉ8ÀÄÔÀäÈÈÙÀÄäÄÔÀÄääàÀÀØÀÀÀ4)ÄÀÈÌÔÌÐäÐààäÉ8ÀÄÔÀäÄÈÙÀÄäÌÄÀÈÀÄàÀÀØÀÀÀ4)ÄÀÈÌÔàÐäÐàäØá8ÀÄÔÀäÄÐÙÀÄäÌäÀÈÀÄÐÀÀØÀÀÀ4)ÄÀÈÐÀÌÐäÐàäÜå8ÀÄÔÀäÈÜÝÀÄäÌØÀÈÀÀÐÀÀØÀÀÀ4)ÄÀÈÐÀàÐäÐàäÄÉ8ÀÄÔÀäÌÐÁÀÄäÐÀÀÈÀÈÐÀÀØÀÀÀ4)ÄÀÈÐÄÌÐäÐààÐÕ8ÀÄÔÀäÈäÙÀÄäÔÈÀÈÀÌÐÀ0
B1024184948844N01509182EA0196402050006000
B1024234948914N01509131EA0197602058006000
```

What is your opinion? Should a possible `relax_line_rule` flag be applicable to L-records (comments as added for instance by SeeYou competition) or to all lines?

**Comment by Turbo87** [comment]
> The idea was to skip invalid B records, such as the following

I guess that B record wouldn't validate anyway, even without this check, right?

> What is your opinion? Should a possible relax_line_rule flag be applicable to L-records (comments as added for instance by SeeYou competition) or to all lines?

IMHO we should remove this line length check completely instead of making it optional

**Comment by GliderGeek** [comment]
> I guess that B record wouldn't validate anyway, even without this check, right?

I don't know. That's definately something that needs to be verified before the line length limitation is removed.

> IMHO we should remove this line length check completely instead of making it optional

Wouldn't it be nice to have the funcionality to check an IGC file on its correct implementation of the spec? (line length is explicitly mentioned in the official FAI doc)

**Comment by Turbo87** [comment]
> I don't know. That's definately something that needs to be verified before the line length limitation is removed.

sure, we should certainly have a unit test for something like the broken record you mentioned in https://github.com/Turbo87/aerofiles/issues/28#issuecomment-371269755

> Wouldn't it be nice to have the funcionality to check an IGC file on its correct implementation of the spec? (line length is explicitly mentioned in the official FAI doc)

in theory yes, but I don't see the practical advantages here. I'd prefer a parser that's close to reality instead of close to the spec.
