### ISSUE TITLE
unknown record type AF

### ISSUE THREAD

**Issue by janzahradka** [Turbo87/aerofiles#283]
I tried to validaty my airspace file by OpenairReader

**I got ValueError: unknown record type AF**.
This tag is used for storing frequencies of the airspace and it's an addition to the original, as written in http://www.winpilot.com/UsersGuide/UserAirspace.asp

validated airspace definition:
```
AC Q
AN DROPZONE Breclav 119.655
AF 119.655
AG Breclav RADIO
AH FL 95
AL 0 AGL
V X=48:47:27 N 016:53:33 E
DC 2 *NM
```

is anyone able to extend the reader with these additional tags?

**Comment by bubeck** [comment]
You are using the OpenAir Extended File format. Currently aerofiles is unable to handle this. However, I am willing to extend it so that it can deal with it. Will need probably 1-2 weeks.

**Comment by bubeck** [comment]
There is now a first implementation ready for test. Could you please try?

**Comment by janzahradka** [comment]
Thank you for such a quick response. I tested it, it can handle AF record now but it raises another error:
`ValueError: could not convert string to float: '2 *NM'` in `handle_DC_record(self, value)`. Perhaps it doesn't ignore the '*NM' comment (I use it each time in DC parameter for preventing units mismatch)

**Comment by bubeck** [comment]
Yes, I will take care. However, early on monday

**Comment by janzahradka** [comment]
[CZ_all_24-08-07.txt](https://github.com/user-attachments/files/16566713/CZ_all_24-08-07.txt)
I can provide my file which i am trying to validate. It's quite complex one.

**Comment by bubeck** [comment]
Parser improved for "*" inside lines, openair/reader can now validate files given on command line.
Above example sucessfully validated.

**Comment by bubeck** [comment]
small problem still.

`Error in file /home/bubeck/Downloads/CZ_all_24-08-07.txt invalid coordinate form at:  50:16:40 N 013:14:06 E`

 wait

**Comment by bubeck** [comment]
Should be OK now to parse your example file. Please let me know.

**Comment by janzahradka** [comment]
Thank you very much, I was on holiday so I get back to it right now. It works! Also thanks for the hint.
