### ISSUE TITLE
problem with parsing igc file

### ISSUE THREAD

**Issue by GliderGeek** [Turbo87/aerofiles#31]
The following igc file (renamed to txt for github upload), does not parse.

[75V_GPS.txt](https://github.com/Turbo87/aerofiles/files/1868105/75V_GPS.txt)

**Comment by Turbo87** [comment]
well... the IGC file standard defines that only ASCII is legal but it seems that Naviter doesn't care about that...

**Comment by GliderGeek** [comment]
same as with the line length ;)

**Comment by Turbo87** [comment]
yep, although in this case there might be different interpretations. I'm pretty sure I've also already seen IGC files where latin1 was used, so it's not that easy to just assume UTF8 🤔

**Comment by GliderGeek** [comment]
i wrongly assumed that latin1 is a subset of utf8 (which it isn't, ascii is a subset of both latin1 and utf-8).

any thoughts on how to detect this?
i guess knowing the source of the igc file might make it predictable (files form soaringspot always have encoding x)

**Comment by Turbo87** [comment]
> any thoughts on how to detect this?

it's complicated... there is no reliable way to detect this. the best-effort variant it reading as utf8 and if that fails trying with latin1 instead, which is what we do in XCSoar too iirc. 

see also https://stackoverflow.com/a/22868803/1478093
